sudo: required
services:
  - docker

before_install:
  - docker build -t justarhymes/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run justarhymes/react-test npm run test -- --coverage

after_success:
  - docker build -t justarhymes/multi-client ./client
  - docker build -t justarhymes/multi-nginx ./nginx
  - docker build -t justarhymes/multi-server ./server
  - docker build -t justarhymes/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push justarhymes/multi-client
  - docker push justarhymes/multi-nginx
  - docker push justarhymes/multi-server
  - docker push justarhymes/multi-worker
